services:
  - type: web
    name: cal-api
    env: docker
    rootDir: backend
    plan: free

    # optional but recommended:
    healthCheckPath: /health

    envVars:
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_PQmCIMV0dU8O@ep-plain-hall-ae269dp6-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require"
      - key: FRONTEND_ORIGIN
        value: "https://cal-frontend.onrender.com"
      - key: PYTHONUNBUFFERED
        value: "1"
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1

  - type: static
    name: cal-frontend
    rootDir: frontend/cal-frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: "https://cal-api.onrender.com"