# render.yaml (put at the repo root)
services:
  - type: web
    name: cal-api
    env: docker
    rootDir: backend
    plan: free
    dockerCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_URL           # set this AFTER the DB is created (step 2)
        sync: false
      - key: FRONTEND_ORIGIN        # set this AFTER the frontend exists (step 4)
        sync: false

  - type: static
    name: cal-frontend
    rootDir: frontend/cal-frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL           # set this AFTER cal-api is live (step 3)
        sync: false

databases:
  - name: cal-db
    plan: free