services:
  - type: web
    name: cal-api
    env: docker
    rootDir: backend
    plan: free
    healthCheckPath: /health
    envVars:
      # Keep this empty to lock CORS to FRONTEND_ORIGIN (recommended).
      # Only set "*" temporarily if you’re debugging CORS.
      - key: EXTRA_CORS_ORIGINS
        value: ""
      - key: PYTHONUNBUFFERED
        value: "1"

  - type: static
    name: cal-frontend
    rootDir: frontend/cal-frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      # Must match your cal-api External URL
      - key: VITE_API_URL
        value: "https://cal-api-otk8.onrender.com"